// Copyright 2021 - 2024, Kia Armani. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace MotionGameplayTags
{
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);

	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_WantsToCrouch);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_IsCrouching);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_IsSprinting);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_IsJumping);
	
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_DisableCameraCollisionCheck);
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_PlayerCannotControlCamera);
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_PlayerCannotControlMovement);
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_PlayerCannotControlAbilities);
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_PlayerCannotControlNativeAbilities);
	MOTIONCORE_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_PlayerCannotControlNativeAbilities);
	MOTIONCORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_MovementHalted);
	

};