// XiaoYao copyright.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace XYSGameplayTags
{
	XYSGAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
	
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Crouch);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Jump);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Pace);
	
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharacterState_Movement_Crouching);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharacterState_Movement_Pacing);
	
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Jump);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Crouch);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Pace);

	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_AbilityInputBlocked);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XYS_Inventory_Message_StackChanged);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XYS_QuickBar_Message_SlotsChanged);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XYS_QuickBar_Message_ActiveIndexChanged);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XYS_Elimination_Message);

	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_Damage);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_DamageImmunity);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_DamageSelfDestruct);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_FellOutOfWorld);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_XYS_Damage_Message);

	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_SIMPLE_FAILURE_MESSAGE);
	XYSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_PLAY_MONTAGE_FAILURE_MESSAGE);

	// Declare all of the custom native tags that XYS will use
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	XYSGAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	XYSGAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
	
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	XYSGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
}
