// Copyright (c) Jared Taylor

#pragma once

#include "NativeGameplayTags.h"

/**
 * Contains tags used by the ProcHitReact plugin.
 */
namespace FHitReactTags
{
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Default);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Default_NoArms);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Default_NoLegs);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Default_NoLimbs);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_BumpPawn);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_TakeHit);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_TakeHit_NoArms);
	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_TakeHit_NoLegs);
	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_TakeHit_NoLimbs);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Twitch);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Twitch_NoArms);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Twitch_NoLegs);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Twitch_NoLimbs);
  	PROCHITREACT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Profile_Flop);
}