;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Respawn.Completed.Message",DevComment="")
+GameplayTagList=(Tag="Ability.Respawn.Duration",DevComment="")
+GameplayTagList=(Tag="Ability.Type.StatusChange.Death",DevComment="")
+GameplayTagList=(Tag="Ability.Type.StatusChange.Spawning",DevComment="")
+GameplayTagList=(Tag="Gameplay.Zone.WeakSpot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.DamageTaken",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Death",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Pistol.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Rifle.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Rifle.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.DamageType.Baisc",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.DamageType.Instant",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.DamageType.M4",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.DamageType.Pistol",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.Aim",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.LeanLeft",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.LeanRight",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.Reload",DevComment="")
+GameplayTagList=(Tag="Status.SpawningIn",DevComment="")
+GameplayTagList=(Tag="XYS.Damage.Taken.Message",DevComment="")
+GameplayTagList=(Tag="XYS.ShooterGame.Weapon.MagazineAmmo",DevComment="")

